# Generated by Django 5.2.1 on 2025-05-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('decription', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
