# Generated by Django 5.2.1 on 2025-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslist',
            name='city',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
