# Generated by Django 5.2.1 on 2025-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hotelslist_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelslist',
            name='pool',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='hotelslist',
            name='restaurant',
            field=models.BooleanField(default='False'),
        ),
    ]
