# Generated by Django 5.2.1 on 2025-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_restaurant_hotelslist_breakfast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelslist',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelslist',
            name='pool',
            field=models.BooleanField(default=False),
        ),
    ]
